version = 1

[[annotations]]
path = "tests/snapshots/*"
SPDX-FileCopyrightText = "2026 Miikka Koskinen"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "Cargo.lock"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
